/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tris;

/**
 *
 * @author Utente
 */
public class TrisCorrettoForm extends javax.swing.JFrame {

    int turno = 0;
    String gioca = "";
    int dim = 3;
    String giocatoreO = "Giocatore O";
    String giocatoreX = "Giocatore X";

    TrisCorretto t = new TrisCorretto(dim, giocatoreX, giocatoreO);

    public TrisCorrettoForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitolo = new javax.swing.JLabel();
        btn00 = new javax.swing.JButton();
        btn02 = new javax.swing.JButton();
        btn01 = new javax.swing.JButton();
        lblTurno = new javax.swing.JLabel();
        txtTurno = new javax.swing.JTextField();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        lblVincitore = new javax.swing.JLabel();
        txtVincitore = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitolo.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        lblTitolo.setText("Tris");

        btn00.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn00ActionPerformed(evt);
            }
        });

        btn02.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn02ActionPerformed(evt);
            }
        });

        btn01.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn01ActionPerformed(evt);
            }
        });

        lblTurno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTurno.setText("Turno: ");

        txtTurno.setEditable(false);
        txtTurno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTurnoActionPerformed(evt);
            }
        });

        btn10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });

        btn11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });

        btn12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });

        btn20.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });

        btn21.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });

        btn22.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });

        lblVincitore.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblVincitore.setText("Vincitore: ");

        txtVincitore.setEditable(false);
        txtVincitore.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtVincitore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVincitoreActionPerformed(evt);
            }
        });

        btnStart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 310, Short.MAX_VALUE)
                .addComponent(lblTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTurno)
                        .addGap(18, 18, 18)
                        .addComponent(txtTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn00, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn01, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn02, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVincitore)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVincitore, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(btnStart)))))
                .addGap(253, 253, 253))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn00, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn01, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn02, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVincitore, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVincitore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnStart)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTurnoActionPerformed

    }//GEN-LAST:event_txtTurnoActionPerformed

    private void txtVincitoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVincitoreActionPerformed

    }//GEN-LAST:event_txtVincitoreActionPerformed

    private void btn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn00ActionPerformed
        if (turno > 1) {
            if (txtTurno.getText().equals(giocatoreX)) {
                txtTurno.setText(giocatoreO);
            } else {
                txtTurno.setText(giocatoreX);
            }
        }

        gioca = t.gioca(0, 0);

        if (txtTurno.getText().equals(giocatoreX)) {
            btn00.setText("X");
        } else {
            btn00.setText("O");
        }

        btn00.setEnabled(false);

        switch (gioca) {
            case "X":
                txtVincitore.setText(giocatoreX);
                break;
            case "O":
                txtVincitore.setText(giocatoreO);
                break;
            case "=":
                txtVincitore.setText("Pareggio");
                break;
            default:
                break;
        }

        turno++;
    }//GEN-LAST:event_btn00ActionPerformed

    private void btn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn01ActionPerformed
        if (turno > 1) {
            if (txtTurno.getText().equals(giocatoreX)) {
                txtTurno.setText(giocatoreO);
            } else {
                txtTurno.setText(giocatoreX);
            }
        }

        gioca = t.gioca(0, 1);

        if (txtTurno.getText().equals(giocatoreX)) {
            btn01.setText("X");
        } else {
            btn01.setText("O");
        }

        btn01.setEnabled(false);

        switch (gioca) {
            case "X":
                txtVincitore.setText(giocatoreX);
                break;
            case "O":
                txtVincitore.setText(giocatoreO);
                break;
            case "=":
                txtVincitore.setText("Pareggio");
                break;
            default:
                break;
        }

        turno++;
    }//GEN-LAST:event_btn01ActionPerformed

    private void btn02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn02ActionPerformed
        if (turno > 1) {
            if (txtTurno.getText().equals(giocatoreX)) {
                txtTurno.setText(giocatoreO);
            } else {
                txtTurno.setText(giocatoreX);
            }
        }

        gioca = t.gioca(0, 2);

        if (txtTurno.getText().equals(giocatoreX)) {
            btn02.setText("X");
        } else {
            btn02.setText("O");
        }

        btn02.setEnabled(false);

        switch (gioca) {
            case "X":
                txtVincitore.setText(giocatoreX);
                break;
            case "O":
                txtVincitore.setText(giocatoreO);
                break;
            case "=":
                txtVincitore.setText("Pareggio");
                break;
            default:
                break;
        }

        turno++;
    }//GEN-LAST:event_btn02ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        if (turno > 1) {
            if (txtTurno.getText().equals(giocatoreX)) {
                txtTurno.setText(giocatoreO);
            } else {
                txtTurno.setText(giocatoreX);
            }
        }

        gioca = t.gioca(1, 0);

        if (txtTurno.getText().equals(giocatoreX)) {
            btn10.setText("X");
        } else {
            btn10.setText("O");
        }

        btn10.setEnabled(false);

        switch (gioca) {
            case "X":
                txtVincitore.setText(giocatoreX);
                break;
            case "O":
                txtVincitore.setText(giocatoreO);
                break;
            case "=":
                txtVincitore.setText("Pareggio");
                break;
            default:
                break;
        }

        turno++;
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        if (turno > 1) {
            if (txtTurno.getText().equals(giocatoreX)) {
                txtTurno.setText(giocatoreO);
            } else {
                txtTurno.setText(giocatoreX);
            }
        }

        gioca = t.gioca(1, 1);

        if (txtTurno.getText().equals(giocatoreX)) {
            btn11.setText("X");
        } else {
            btn11.setText("O");
        }

        btn11.setEnabled(false);

        switch (gioca) {
            case "X":
                txtVincitore.setText(giocatoreX);
                break;
            case "O":
                txtVincitore.setText(giocatoreO);
                break;
            case "=":
                txtVincitore.setText("Pareggio");
                break;
            default:
                break;
        }

        turno++;
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        if (turno > 1) {
            if (txtTurno.getText().equals(giocatoreX)) {
                txtTurno.setText(giocatoreO);
            } else {
                txtTurno.setText(giocatoreX);
            }
        }

        gioca = t.gioca(1, 2);

        if (txtTurno.getText().equals(giocatoreX)) {
            btn12.setText("X");
        } else {
            btn12.setText("O");
        }

        btn12.setEnabled(false);

        switch (gioca) {
            case "X":
                txtVincitore.setText(giocatoreX);
                break;
            case "O":
                txtVincitore.setText(giocatoreO);
                break;
            case "=":
                txtVincitore.setText("Pareggio");
                break;
            default:
                break;
        }

        turno++;
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        if (turno > 1) {
            if (txtTurno.getText().equals(giocatoreX)) {
                txtTurno.setText(giocatoreO);
            } else {
                txtTurno.setText(giocatoreX);
            }
        }

        gioca = t.gioca(2, 0);

        if (txtTurno.getText().equals(giocatoreX)) {
            btn20.setText("X");
        } else {
            btn20.setText("O");
        }

        btn20.setEnabled(false);

        switch (gioca) {
            case "X":
                txtVincitore.setText(giocatoreX);
                break;
            case "O":
                txtVincitore.setText(giocatoreO);
                break;
            case "=":
                txtVincitore.setText("Pareggio");
                break;
            default:
                break;
        }

        turno++;
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
        if (turno > 1) {
            if (txtTurno.getText().equals(giocatoreX)) {
                txtTurno.setText(giocatoreO);
            } else {
                txtTurno.setText(giocatoreX);
            }
        }

        gioca = t.gioca(2, 1);

        if (txtTurno.getText().equals(giocatoreX)) {
            btn21.setText("X");
        } else {
            btn21.setText("O");
        }

        btn21.setEnabled(false);

        switch (gioca) {
            case "X":
                txtVincitore.setText(giocatoreX);
                break;
            case "O":
                txtVincitore.setText(giocatoreO);
                break;
            case "=":
                txtVincitore.setText("Pareggio");
                break;
            default:
                break;
        }

        turno++;
    }//GEN-LAST:event_btn21ActionPerformed

    private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
        if (turno > 1) {
            if (txtTurno.getText().equals(giocatoreX)) {
                txtTurno.setText(giocatoreO);
            } else {
                txtTurno.setText(giocatoreX);
            }
        }

        gioca = t.gioca(2, 2);

        if (txtTurno.getText().equals(giocatoreX)) {
            btn22.setText("X");
        } else {
            btn22.setText("O");
        }

        btn22.setEnabled(false);

        switch (gioca) {
            case "X":
                txtVincitore.setText(giocatoreX);
                break;
            case "O":
                txtVincitore.setText(giocatoreO);
                break;
            case "=":
                txtVincitore.setText("Pareggio");
                break;
            default:
                break;
        }

        turno++;
    }//GEN-LAST:event_btn22ActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        txtTurno.setText(giocatoreX);
        turno++;
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrisCorrettoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrisCorrettoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrisCorrettoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrisCorrettoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrisCorrettoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn00;
    private javax.swing.JButton btn01;
    private javax.swing.JButton btn02;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JLabel lblVincitore;
    private javax.swing.JTextField txtTurno;
    private javax.swing.JTextField txtVincitore;
    // End of variables declaration//GEN-END:variables
}
