/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tris;

/**
 *
 * @author luca.negriolli
 */
public class TrisForm extends javax.swing.JFrame {

    /**
     * Creates new form TrisForm
     */
    public TrisForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLanciaMoneta = new javax.swing.JButton();
        txtMoneta = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        txtTurno = new javax.swing.JTextField();
        txtTurno1 = new javax.swing.JTextField();
        txtVincitore = new javax.swing.JTextField();
        txtVincitore1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLanciaMoneta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLanciaMoneta.setText("Lancia la moneta");
        btnLanciaMoneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanciaMonetaActionPerformed(evt);
            }
        });

        txtMoneta.setEditable(false);
        txtMoneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMonetaActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jTextField1.setText("Tris");

        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        txtTurno.setEditable(false);
        txtTurno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTurno.setText("Tocca a:");

        txtTurno1.setEditable(false);
        txtTurno1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTurno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTurno1ActionPerformed(evt);
            }
        });

        txtVincitore.setText("Vincitore");
        txtVincitore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVincitoreActionPerformed(evt);
            }
        });

        txtVincitore1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVincitore1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLanciaMoneta, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMoneta, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(178, 178, 178)
                                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(50, 50, 50)
                                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtTurno1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(55, 55, 55)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtVincitore, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(txtVincitore1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLanciaMoneta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMoneta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTurno1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVincitore, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVincitore1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLanciaMonetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanciaMonetaActionPerformed
        // TODO add your handling code here:
        String g1 = "Giocatore 1", g2 = "Giocatore 2";
        Tris t = new Tris(g1, g2);

        int ris = t.moneta();

        if (ris == 0) {
            txtMoneta.setText(g1);
            txtTurno1.setText(g1);
        } else {
            txtMoneta.setText(g2);
            txtTurno1.setText(g2);
        }
        btnLanciaMoneta.setEnabled(false);
    }//GEN-LAST:event_btnLanciaMonetaActionPerformed

    private void txtMonetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMonetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMonetaActionPerformed

    private void txtTurno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTurno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTurno1ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        String g1 = "Giocatore 1", g2 = "Giocatore 2";
        Tris t = new Tris(g1, g2);

        int posX = 0, posY = 0;
        btn1.setEnabled(false);
        if (txtTurno1.getText().equals("Giocatore 1")) {
            if (t.mossaG1(posX, posY) == true) {
                txtTurno1.setText(g2);
                btn1.setText("X");
            }
        } else {
            if (t.mossaG2(posX, posY) == true) {
                txtTurno1.setText(g1);
                btn1.setText("O");
            }
        }
        if(t.controllo(t.getCampoDaGioco()) == true){
            if(txtTurno1.getText().equals("Giocatore 1")){
                txtVincitore1.setText(g2);
            }else{
                txtVincitore1.setText(g1);
            }
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        String g1 = "Giocatore 1", g2 = "Giocatore 2";
        Tris t = new Tris(g1, g2);

        int posX = 0, posY = 1;
        btn2.setEnabled(false);
        if (txtTurno1.getText().equals("Giocatore 1")) {
            if (t.mossaG1(posX, posY) == true) {
                txtTurno1.setText(g2);
                btn2.setText("X");
            }
        } else {
            if (t.mossaG2(posX, posY) == true) {
                txtTurno1.setText(g1);
                btn2.setText("O");
            }
        }
        if(t.controllo(t.getCampoDaGioco()) == true){
            if(txtTurno1.getText().equals("Giocatore 1")){
                txtVincitore1.setText(g2);
            }else{
                txtVincitore1.setText(g1);
            }
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        String g1 = "Giocatore 1",g2 = "Giocatore 2";
        Tris t = new Tris(g1, g2);
        
        int posX = 1,posY = 0;
        btn4.setEnabled(false);
        if(txtTurno1.getText().equals("Giocatore 1")){
            if(t.mossaG1(posX, posY) == true){
                txtTurno1.setText(g2);
                btn4.setText("X");
            }
        }else{
            if(t.mossaG2(posX, posY) == true){
                txtTurno1.setText(g1);
                btn4.setText("O");
            }
        }
        if(t.controllo(t.getCampoDaGioco()) == true){
            if(txtTurno1.getText().equals("Giocatore 1")){
                txtVincitore1.setText(g2);
            }else{
                txtVincitore1.setText(g1);
            }
        }

    }//GEN-LAST:event_btn4ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        String g1 = "Giocatore 1",g2 = "Giocatore 2";
        Tris t = new Tris(g1, g2);
        
        int posX = 2,posY = 1;
        btn8.setEnabled(false);
        if(txtTurno1.getText().equals("Giocatore 1")){
            if(t.mossaG1(posX, posY) == true){
                txtTurno1.setText(g2);
                btn8.setText("X");
            }
        }else{
            if(t.mossaG2(posX, posY) == true){
                txtTurno1.setText(g1);
                btn8.setText("O");
            }
        }
        if(t.controllo(t.getCampoDaGioco()) == true){
            if(txtTurno1.getText().equals("Giocatore 1")){
                txtVincitore1.setText(g2);
            }else{
                txtVincitore1.setText(g1);
            }
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add  handling code here:
        String g1 = "Giocatore 1",g2 = "Giocatore 2";
        Tris t = new Tris(g1, g2);
        
        int posX = 0,posY = 2;
        btn3.setEnabled(false);
        if(txtTurno1.getText().equals("Giocatore 1")){
            if(t.mossaG1(posX, posY) == true){
                txtTurno1.setText(g2);
                btn3.setText("X");
            }
        }else{
            if(t.mossaG2(posX, posY) == true){
                txtTurno1.setText(g1);
                btn3.setText("O");
            }
        }
        if(t.controllo(t.getCampoDaGioco()) == true){
            if(txtTurno1.getText().equals("Giocatore 1")){
                txtVincitore1.setText(g2);
            }else{
                txtVincitore1.setText(g1);
            }
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        String g1 = "Giocatore 1",g2 = "Giocatore 2";
        Tris t = new Tris(g1, g2);
        
        int posX = 1,posY = 1;
        btn5.setEnabled(false);
        if(txtTurno1.getText().equals("Giocatore 1")){
            if(t.mossaG1(posX, posY) == true){
                txtTurno1.setText(g2);
                btn5.setText("X");
            }
        }else{
            if(t.mossaG2(posX, posY) == true){
                txtTurno1.setText(g1);
                btn5.setText("O");
            }
        }
        if(t.controllo(t.getCampoDaGioco()) == true){
            if(txtTurno1.getText().equals("Giocatore 1")){
                txtVincitore1.setText(g2);
            }else{
                txtVincitore1.setText(g1);
            }
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        String g1 = "Giocatore 1",g2 = "Giocatore 2";
        Tris t = new Tris(g1, g2);
        
        int posX = 1,posY = 2;
        btn6.setEnabled(false);
        if(txtTurno1.getText().equals("Giocatore 1")){
            if(t.mossaG1(posX, posY) == true){
                txtTurno1.setText(g2);
                btn6.setText("X");
            }
        }else{
            if(t.mossaG2(posX, posY) == true){
                txtTurno1.setText(g1);
                btn6.setText("O");
            }
        }
        if(t.controllo(t.getCampoDaGioco()) == true){
            if(txtTurno1.getText().equals("Giocatore 1")){
                txtVincitore1.setText(g2);
            }else{
                txtVincitore1.setText(g1);
            }
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        String g1 = "Giocatore 1",g2 = "Giocatore 2";
        Tris t = new Tris(g1, g2);
        
        int posX = 2,posY = 0;
        btn7.setEnabled(false);
        if(txtTurno1.getText().equals("Giocatore 1")){
            if(t.mossaG1(posX, posY) == true){
                txtTurno1.setText(g2);
                btn7.setText("X");
            }
        }else{
            if(t.mossaG2(posX, posY) == true){
                txtTurno1.setText(g1);
                btn7.setText("O");
            }
        }
        if(t.controllo(t.getCampoDaGioco()) == true){
            if(txtTurno1.getText().equals("Giocatore 1")){
                txtVincitore1.setText(g2);
            }else{
                txtVincitore1.setText(g1);
            }
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        String g1 = "Giocatore 1",g2 = "Giocatore 2";
        Tris t = new Tris(g1, g2);
        
        int posX = 2,posY = 2;
        btn9.setEnabled(false);
        if(txtTurno1.getText().equals("Giocatore 1")){
            if(t.mossaG1(posX, posY) == true){
                txtTurno1.setText(g2);
                btn9.setText("X");
            }
        }else{
            if(t.mossaG2(posX, posY) == true){
                txtTurno1.setText(g1);
                btn9.setText("O");
            }
        }
        if(t.controllo(t.getCampoDaGioco()) == true){
            if(txtTurno1.getText().equals("Giocatore 1")){
                txtVincitore1.setText(g2);
            }else{
                txtVincitore1.setText(g1);
            }
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void txtVincitore1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVincitore1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVincitore1ActionPerformed

    private void txtVincitoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVincitoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVincitoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrisForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnLanciaMoneta;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtMoneta;
    private javax.swing.JTextField txtTurno;
    private javax.swing.JTextField txtTurno1;
    private javax.swing.JTextField txtVincitore;
    private javax.swing.JTextField txtVincitore1;
    // End of variables declaration//GEN-END:variables
}
