/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cicli;

import java.util.Arrays;

/**
 *
 * @author Utente
 */
public class CifrarioDiCesareForm extends javax.swing.JFrame {

    /**
     * Creates new form CifrarioDiCesareForm
     */
    public CifrarioDiCesareForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitolo = new javax.swing.JLabel();
        txtStringaInput = new javax.swing.JTextField();
        lblStringaInput = new javax.swing.JLabel();
        lblStringaOutput = new javax.swing.JLabel();
        txtStringaOutput = new javax.swing.JTextField();
        btnCodifica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitolo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitolo.setText("Cifrario di Cesare");

        txtStringaInput.setEditable(false);
        txtStringaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStringaInputActionPerformed(evt);
            }
        });

        lblStringaInput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStringaInput.setText("Stringa");

        lblStringaOutput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStringaOutput.setText("Stringa Cifrata");

        txtStringaOutput.setEditable(false);

        btnCodifica.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCodifica.setText("Codifica");
        btnCodifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodificaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(lblTitolo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStringaOutput)
                            .addComponent(lblStringaInput))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtStringaInput)
                            .addComponent(txtStringaOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btnCodifica, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblTitolo)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStringaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStringaInput))
                .addGap(31, 31, 31)
                .addComponent(btnCodifica, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStringaOutput)
                    .addComponent(txtStringaOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStringaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStringaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStringaInputActionPerformed

    private void btnCodificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodificaActionPerformed
        String str = txtStringaInput.getText();
        
        CifrarioDiCesare cf = new CifrarioDiCesare(str);
        
        txtStringaOutput.setText(cf.ritornaStringa());
        
    }//GEN-LAST:event_btnCodificaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CifrarioDiCesareForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CifrarioDiCesareForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CifrarioDiCesareForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CifrarioDiCesareForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CifrarioDiCesareForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCodifica;
    private javax.swing.JLabel lblStringaInput;
    private javax.swing.JLabel lblStringaOutput;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JTextField txtStringaInput;
    private javax.swing.JTextField txtStringaOutput;
    // End of variables declaration//GEN-END:variables
}
