/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package figureGeometriche;

/**
 *
 * @author luca.negriolli
 */
public class TriangoloGenericoForm extends javax.swing.JFrame {
    TriangoloGenerico t;
    /**
     * Creates new form TriangoloForm
     */
    public TriangoloGenericoForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTriangolo = new javax.swing.JLabel();
        lblLato1 = new javax.swing.JLabel();
        txtLato1 = new javax.swing.JTextField();
        lblLato2 = new javax.swing.JLabel();
        txtLato2 = new javax.swing.JTextField();
        lblLato3 = new javax.swing.JLabel();
        txtLato3 = new javax.swing.JTextField();
        lblDatiDiOutput = new javax.swing.JLabel();
        lblDatiDiInput1 = new javax.swing.JLabel();
        lblPerimetro = new javax.swing.JLabel();
        txtPerimetro = new javax.swing.JTextField();
        btnCalcola = new javax.swing.JButton();
        lblArea = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTriangolo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTriangolo.setText("Programma per operazioni sul Triangolo");

        lblLato1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLato1.setText("Lato 1");

        txtLato1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLato1ActionPerformed(evt);
            }
        });

        lblLato2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLato2.setText("Lato 2");

        txtLato2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLato2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLato2ActionPerformed(evt);
            }
        });

        lblLato3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLato3.setText("Lato 3");

        txtLato3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLato3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLato3ActionPerformed(evt);
            }
        });

        lblDatiDiOutput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDatiDiOutput.setText("Dati di Output");

        lblDatiDiInput1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDatiDiInput1.setText("Dati di Input");

        lblPerimetro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPerimetro.setText("Perimetro");

        txtPerimetro.setEditable(false);
        txtPerimetro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerimetroActionPerformed(evt);
            }
        });

        btnCalcola.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCalcola.setText("Calcola");
        btnCalcola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcolaActionPerformed(evt);
            }
        });

        lblArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblArea.setText("Area");

        txtArea.setEditable(false);
        txtArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDatiDiInput1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLato2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLato2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLato3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLato3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLato1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLato1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblDatiDiOutput)
                                .addGap(72, 72, 72))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCalcola)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblArea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(lblPerimetro)
                                .addGap(8, 8, 8)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPerimetro, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(txtArea))
                        .addGap(41, 41, 41))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTriangolo)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTriangolo)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatiDiInput1)
                    .addComponent(lblDatiDiOutput))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLato1)
                            .addComponent(txtLato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLato2)
                            .addComponent(txtLato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLato3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtLato3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCalcola))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPerimetro)
                            .addComponent(txtPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblArea)
                            .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLato1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLato1ActionPerformed

    private void txtLato2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLato2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLato2ActionPerformed

    private void txtLato3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLato3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLato3ActionPerformed

    private void txtPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerimetroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerimetroActionPerformed

    private void btnCalcolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcolaActionPerformed
        float n1 = Float.parseFloat(txtLato1.getText());
        float n2 = Float.parseFloat(txtLato2.getText());
        float n3 = Float.parseFloat(txtLato3.getText());
        
        t = new TriangoloGenerico(n1, n2, n3);
        
        float p = t.perimetro();
        
        float a = t.area();
        
        txtPerimetro.setText(String.valueOf(p));
        
        txtArea.setText(String.valueOf(a));
    }//GEN-LAST:event_btnCalcolaActionPerformed

    private void txtAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TriangoloGenericoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TriangoloGenericoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TriangoloGenericoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TriangoloGenericoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TriangoloGenericoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcola;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblDatiDiInput1;
    private javax.swing.JLabel lblDatiDiOutput;
    private javax.swing.JLabel lblLato1;
    private javax.swing.JLabel lblLato2;
    private javax.swing.JLabel lblLato3;
    private javax.swing.JLabel lblPerimetro;
    private javax.swing.JLabel lblTriangolo;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtLato1;
    private javax.swing.JTextField txtLato2;
    private javax.swing.JTextField txtLato3;
    private javax.swing.JTextField txtPerimetro;
    // End of variables declaration//GEN-END:variables
}
